### ISSUE TITLE
Setting failover extension and getting status

### ISSUE THREAD

**Issue by jperez3** [f5devcentral/f5-cloud-failover-extension#2]
I'm trying to set up the failover extension and starting with a curl to the info endpoint:
```
curl -ku admin:password123 -H "Content-Type:  application/json" https://localhost/mgmt/shared/cloud-failover/info
{"version":"0.9.1","release":"1","schemaCurrent":"0.9.0","schemaMinimum":"0.9.0"}
``` 

It appears that this get request to "info" works, but when I try to do the `POST` to configure the failover extension. I start to see errors.

```
curl -X POST -d @/tmp/failover_config.json -ku admin:password123 -H "Content-Type:  application/json" https://localhost/mgmt/shared/cloud-failover/declare
{"code":400,"message":"remoteSender:127.0.0.1, method:POST ","originalRequestBody":"{    \"class\": \"Cloud_Failover\",    \"environment\": \"aws\",    \"externalStorage\": {        \"scopingTags\": {            \"F5_Cluster\": \"f5_unique_cluster_name1\"        }    },    \"failoverAddresses\": {        \"scopingTags\": {            \"F5_Cluster\": \"f5_unique_cluster_name1\"        }    },    \"failoverRoutes\": {        \"scopingTags\": {            \"F5_Cluster\": \"f5_unique_cluster_name1\"        },        \"scopingAddressRanges\": [            \"10.0.0.0/24\"        ]    }}","referer":"127.0.0.1","restOperationId":8835633,"errorStack":["java.util.concurrent.TimeoutException: remoteSender:127.0.0.1, method:POST ","at com.f5.rest.common.RestWorker.logAndFailExpiredOperation(RestWorker.java:3168)","at com.f5.rest.common.RestWorker.checkForExpiredOperations(RestWorker.java:3157)","at com.f5.rest.common.RestServer.checkAndExpirePendingWorkerOperations(RestServer.java:1263)","at com.f5.rest.common.RestServer.access$200(RestServer.java:44)","at com.f5.rest.common.RestServer$3.run(RestServer.java:1236)","at com.f5.rest.common.ScheduleTaskManager$2$1.run(ScheduleTaskManager.java:123)","at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)","at java.util.concurrent.FutureTask.run(FutureTask.java:262)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)","at java.util.concurrent.ThreadPoolExecutor.runWorker(Th
```

then I'm seeing a bunch of auth errors in `/var/log/restnoded/restnoded.log`:

```
Thu, 12 Dec 2019 23:17:38 GMT - finer: [f5-cloud-failover: device.js] tryUntil error: Access Denied tries left: 11
Thu, 12 Dec 2019 23:17:38 GMT - finest: [f5-cloud-failover: device.js] tryUntil: retryOrReject: numRemaining: 11 , code: AccessDenied , message: Access Denied
```

Additional info:
Cloud Provider: AWS
AMI: ami-03b18799f246d2695 (PAYG)
F5 Version: BIG-IP 15.0.1 Build 0.0.11 Final

**Comment by jperez3** [comment]
json file:
```
cat /tmp/failover_config.json 
{
    "class": "Cloud_Failover",
    "environment": "aws",
    "externalStorage": {
        "scopingTags": {
            "F5_Cluster": "f5_unique_cluster_name1"
        }
    },
    "failoverAddresses": {
        "scopingTags": {
            "F5_Cluster": "f5_unique_cluster_name1"
        }
    },
    "failoverRoutes": {
        "scopingTags": {
            "F5_Cluster": "f5_unique_cluster_name1"
        },
        "scopingAddressRanges": [
            "10.0.0.0/24"
        ]
    }
}
```

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with your issue.

Roles with the correct policy permissions need to be added to each instance. Directions on how to do so can be found here:

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#creating-and-assigning-an-iam-role

Once the roles are added, you'll be able to post a declaration.

**Comment by alaari-f5** [comment]
Pls refer to Shyawn's comment. If you have further questions or require additional help, pls feel free to reach out. Closing this issue for now.
